[project]
name = "astral-oddities"
version = "0.1.0"
description = "Starter project for Astral Oddities"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

